name: 🚀 Deploy

on:
  push:
    branches:
      - main
      - dev
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: ⬣ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: ./package.json
          node-version: 22

      - name: 📥 Install deps
        run: npm ci

      - name: 🔬 Lint
        run: npm run lint

  typecheck:
    name: ʦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: ./package.json
          node-version: 22

      - name: 📥 Install deps
        run: npm ci

      - name: 🔎 Type check
        run: npm run typecheck --if-present

  vitest:
    name: ⚡ Vitest
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: ./package.json
          node-version: 22

      - name: 📥 Install deps
        run: npm ci

      - name: ⚡ Run vitest
        run: npm run test -- --coverage

  # playwright:
  #   name: 🎭 Playwright
  #   runs-on: ubuntu-latest
  #   env:
  #     NODE_ENV: "test"
  #     SESSION_SECRET: "test-session-secret-for-ci"
  #     ARC_APP_SECRET: "test-arc-app-secret-for-ci"
  #   steps:
  #     - name: ⬇️ Checkout repo
  #       uses: actions/checkout@v4
  #
  #     - name: 🏄 Copy test env vars
  #       run: cp .env.example .env
  #
  #     - name: ⎔ Setup node
  #       uses: actions/setup-node@v4
  #       with:
  #         cache: npm
  #         cache-dependency-path: ./package.json
  #         node-version: 22
  #
  #     - name: 📥 Install deps
  #       run: npm install
  #
  #     - name: 🎭 Install Playwright browsers
  #       run: npx playwright install --with-deps
  #
  #     - name: 🏗 Build
  #       run: npm run build
  #
  #     - name: 🎭 Playwright run
  #       run: |
  #         echo "NODE_ENV: $NODE_ENV"
  #         echo "SESSION_SECRET: $SESSION_SECRET"
  #         echo "ARC_APP_SECRET: $ARC_APP_SECRET"
  #         npm run test:e2e
  #       env:
  #         PORT: "3333"

  deploy:
    needs: [lint, typecheck, vitest]
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: ./package.json
          node-version: 22

      - name: 👀 Env
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Git ref:    ${{ github.ref }}"
          echo "GH actor:   ${{ github.actor }}"
          echo "SHA:        ${{ github.sha }}"
          VER=`node --version`; echo "Node ver:   $VER"
          VER=`npm --version`; echo "npm ver:    $VER"

      - name: 📥 Install deps
        run: npm ci

      - name: 🏗 Build
        run: npm run build

      - name: 🔐 Configure AWS (staging)
        if: github.ref == 'refs/heads/dev'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::439882680258:role/Choosinator-DeployRole-Staging
          aws-region: us-west-2

      - name: 🚀 Arc deploy (staging)
        if: github.ref == 'refs/heads/dev'
        run: npx arc deploy --staging --prune
        env:
          CI: true

      - name: 🔐 Configure AWS (prod)
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::439882680258:role/Choosinator-DeployRole-Production
          aws-region: us-west-2

      - name: 🚀 Arc deploy (prod)
        if: github.ref == 'refs/heads/main'
        run: npx arc deploy --production --prune
        env:
          CI: true
